created a new repository Online Book Store
aksoli666/book_store pull request #1
Opened 2024-03-28 06:57 UTC by aksoli666

+created a Spring Boot project with pom.xml file with all required dependencies
+added Book entity
+added BookRepository
+added BookService
+configured database access
+configured checkstyle
+configured application.properties in the test/resources folder +configured CI
+configure GitHub git branch flow

2024-03-28 10:34 UTC, Rommelua requested changes

2024-03-28 10:34 UTC, Rommelua commented on src/main/java/book/store/model/Book.java
> +@Data
do not use @Data in Entity class

2024-03-28 10:34 UTC, Rommelua commented on src/main/java/book/store/model/Book.java
> +    private String isbn;
add unique constraint

2024-03-28 10:34 UTC, Rommelua commented on src/test/java/book/store/BookStoreApplicationTests.java
> -	}
do not delete this test

2024-04-02 14:50 UTC, kerrrusha approved these changes

2024-04-04 11:58 UTC, MAMentorFX approved these changes

2024-04-04 11:58 UTC, MAMentorFX commented on src/main/java/book/store/controller/CreateBookRequestDto.java
> +@ToString
For DTOs we can use @Data :)

2024-04-04 11:58 UTC, MAMentorFX commented on src/main/java/book/store/model/Book.java
> +    @ToString.Exclude
@ToString(exclude = {}) for class level instead of field level @ToString.Exclude. Imagine you need to exclude so many fields, it requires too many @ToString.Exclude
Also please explain why do we need to Exclude ToString for ISBN though, is it requirement?

2024-04-04 11:58 UTC, MAMentorFX commented on src/main/java/book/store/model/Book.java
> +    private String isbn;
fixed

2024-04-04 11:58 UTC, MAMentorFX commented on src/main/java/book/store/service/impl/BookServiceImpl.java
> +                .stream()
```suggestion
        return bookRepository.findAll().stream()
```

2024-04-08 11:57 UTC, merged